spring:
  profiles: default
  datasource:
      driver-class-name: org.postgresql.Driver
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
  jpa:
      show-sql: false
      properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
          ddl-auto: update
          naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
security:
  require-ssl: true
server:
  port: 8444
  error:
    whitelabel:
      enabled: false
  ssl:
    key-store: ${KEY_FILE}
    key-store-password: ${KEY_FILE_PASSWORD}
    keyStoreType: PKCS12
    keyAlias: tomcat
kidsclub:
  admin: ${ADMIN_EMAIL}
  google:
    client:
      clientId: ${GOOGLE_CLIENT_ID}
      clientSecret: ${GOOGLE_CLIENT_SECRET}
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile email
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false

---
spring:
  profiles: prod
  datasource:
      driver-class-name: org.postgresql.Driver
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
  jpa:
      show-sql: false
      properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
          ddl-auto: update
          naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
security:
  require-ssl: true
server:
  port: 8443
  error:
    whitelabel:
      enabled: false
  ssl:
    key-store: ${KEY_FILE}
    key-store-password: ${KEY_FILE_PASSWORD}
    keyStoreType: PKCS12
    keyAlias: tomcat
kidsclub:
  admin: ${ADMIN_EMAIL}
  google:
    client:
      clientId: ${GOOGLE_CLIENT_ID}
      clientSecret: ${GOOGLE_CLIENT_SECRET}
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile email
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false

---
